version: "3.9"

services:
  orderservice:
    build:
      context: ./services/OrderService/OrderService.Api
    container_name: orderservice
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  authservice:
    build:
      context: ./services/AuthService
    container_name: authservice
    ports:
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development