services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"  
    depends_on:
      - orderservice
      - authservice

  orderservice:
    build:
      context: ../backend/services/OrderService/OrderService.Api
    container_name: orderservice
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Connection=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Jwt__Key=SUPER_SECRET_KEY_MICROSERVICOS_2026_ORDER_AUTH_1234567890123456
      - Jwt__Issuer=AuthService
      - Jwt__Audience=OrderService
    depends_on:
      - redis
      - rabbitmq  
  
  authservice:
    build:
      context: ../backend/services/AuthService
    container_name: authservice
    ports:
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Connection=redis:6379
      - Jwt__Key=SUPER_SECRET_KEY_MICROSERVICOS_2026_ORDER_AUTH_1234567890123456
      - Jwt__Issuer=AuthService
      - Jwt__Audience=OrderService

  auditservice:
    build:
      context: ../backend/services/AuditService/AuditService.Api      
    container_name: auditservice
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq     

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"   