version: "3.9"

services:
  orderservice:
    build:
      context: ../backend/services/OrderService/OrderService.Api
    container_name: orderservice
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  authservice:
    build:
      context: ../backend/services/AuthService
    container_name: authservice
    ports:
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=SUPER_SECRET_KEY_MICROSERVICOS_2026_ORDER_AUTH_1234567890123456
      - Jwt__Issuer=AuthService
      - Jwt__Audience=OrderService